---
- hosts: webservers
  vars:
    variable_to_be_replaced: 'Hello world'
    inline_variable: 'hello again'
  tasks:
   - name: Ansible Template Example
     template:
      src: /playbooks/Jinja_loop.j2
      dest: /root/reading/Jinja_loop.txt
      mode: 0655
