---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Copying .Sh file for installation
    copy: src=/tmp/test1.sh dest=/tmp/
  - name: Executing shell file
    command: sh /tmp/test1.sh
