---
- hosts: webservers
  become: true
  become_user: root
  tasks:  
   - name: Set a fact 
     set_fact:
      fact_val: "Ansible Rocks !!"  
   - name: Show a fact
     debug:     
      msg: "{{ fact_val }}"

