---
- hosts: webservers
  become: true
  become_user: root
  tasks:  
   - set_fact:
      fact_time: "Fact: {{lookup('pipe', 'date \"+%H:%M:%S\"')}}"  
   - debug: var=fact_time
   - command: sleep 2
   - debug: var=fact_time

