---
- hosts: webservers
  become: true
  become_user: root
  tasks:  
   - name: Set a fact 
     set_fact:
      fact_val: " Ansible Rocks !!"
      ansible_distribution: "{{ ansible_distribution | upper }}"
   - name: wait for webserver to check the status of jenkins application
     wait_for:
      path: /etc/init.d/jenkins
      state: started 
   - name: Show a fact
     debug:     
      msg: "{{ fact_val }}"
   - name: Show ansible distribution
     debug:
      msg: "{{ ansible_distribution }}"

